INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Hans Karlsson', 51,'hans@hotmail.com','Land scraper','Stockholm');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Peter Pan', 40,'peter@hotmail.com','Dog Sitter','Västerås');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Hans Andersson', 59,'hans@hotmail.com','Plumber','Stockholm');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Anna Pedersen', 46,'hanna@hotmail.com','Nurse','Uppsala');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Jens Ortner', 31,'Jens.ortner@appliedtechnology.se','Java developer','Stockholm');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Måns Ortner', 35,'mans@hotmail.com','Sound engineer','Stockholm');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Trille Ortner', 31,'trille@hotmail.com','Occupational therapist','Upplands Väsby');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Andreas Svensson', 44,'a.svensson@hotmail.com','mechanical engineer','Gävle');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Noa Gustavson', 32,'noa@hotmail.com','Truck driver','Uppsala');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city) VALUES ('Karl Mosesson', 43,'hans@hotmail.com','Chef','Täby');
