INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Hans Karlsson', 51,'hans@hotmail.com','Land scraper','Stockholm','https://avatar.iran.liara.run/public/1');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Peter Pan', 40,'peter@hotmail.com','Dog Sitter','Västerås','https://avatar.iran.liara.run/public/2');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Hans Andersson', 59,'hans@hotmail.com','Plumber','Stockholm','https://avatar.iran.liara.run/public/3');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Anna Pedersen', 46,'hanna@hotmail.com','Nurse','Uppsala','https://avatar.iran.liara.run/public/78');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Måns Ortner', 35,'mans@hotmail.com','Sound engineer','Stockholm','https://avatar.iran.liara.run/public/5');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Trille Ortner', 31,'trille@hotmail.com','Occupational therapist','Upplands Väsby','https://avatar.iran.liara.run/public/6');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Andreas Svensson', 44,'a.svensson@hotmail.com','mechanical engineer','Gävle','https://avatar.iran.liara.run/public/7');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Noa Gustavson', 32,'noa@hotmail.com','Truck driver','Uppsala','https://avatar.iran.liara.run/public/8');
INSERT INTO volunteer(volunteer_name, volunteer_age, volunteer_email,volunteer_occupation,volunteer_city,volunteer_imgurl) VALUES ('Karl Mosesson', 43,'hans@hotmail.com','Chef','Täby','https://avatar.iran.liara.run/public/9');
